springdoc:
  swagger-ui:
    path: /docs.html
  api-docs:
    path: /api-docs
    groups:
      enabled: false
spring:
 datasource:
  url: ${DATABASE_URL}
  driver-class-name: org.postgresql.Driver
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true
   hibernate:
    ddl-auto: none
server:
  port: 8080

security.jwt:
  expricao: 120
  chave-assinatura: ${APP_SECRET}
