spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cad-funcionarios
    username: postgres
    password: 2020Banco
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        lob:
          non_contextual_creation: 'true'
  

server:
  port: 8081