
spring:
 datasource:
  url: jdbc:postgresql://dpg-ckomhck1tcps73antitg-a:5432/rhservice
  driver-class-name: org.postgresql.Driver
  username: joaobelmiro
  password: yinTG5nuI7JwnMah0poK3xfZGc6VwhKg
 jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true
   hibernate:
    ddl-auto: none
server:
  port: 8080

security.jwt:
  expricao: 120
  chave-assinatura: am9hbyBjYXJsb3MgYmVsbWlybyBnb27Dp2FsdmVz
